/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedCalculatorSettingsRouteImport } from './routes/_protected/calculator-settings'
import { Route as ProtectedProjectsRouteImport } from './routes/_protected/projects'
import { Route as ProtectedAdminsIndexRouteImport } from './routes/_protected/admins/index'
import { Route as ProtectedEnquiriesIndexRouteImport } from './routes/_protected/enquiries/index'
import { Route as ProtectedEnquiriesIdRouteImport } from './routes/_protected/enquiries/$id'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCalculatorSettingsRoute =
  ProtectedCalculatorSettingsRouteImport.update({
    id: '/calculator-settings',
    path: '/calculator-settings',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProjectsRoute = ProtectedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminsIndexRoute = ProtectedAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEnquiriesIndexRoute = ProtectedEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEnquiriesIdRoute = ProtectedEnquiriesIdRouteImport.update({
  id: '/enquiries/$id',
  path: '/enquiries/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/calculator-settings': typeof ProtectedCalculatorSettingsRoute
  '/projects': typeof ProtectedProjectsRoute
  '/enquiries/$id': typeof ProtectedEnquiriesIdRoute
  '/admins/': typeof ProtectedAdminsIndexRoute
  '/enquiries/': typeof ProtectedEnquiriesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calculator-settings': typeof ProtectedCalculatorSettingsRoute
  '/projects': typeof ProtectedProjectsRoute
  '/': typeof ProtectedIndexRoute
  '/enquiries/$id': typeof ProtectedEnquiriesIdRoute
  '/admins': typeof ProtectedAdminsIndexRoute
  '/enquiries': typeof ProtectedEnquiriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/calculator-settings': typeof ProtectedCalculatorSettingsRoute
  '/_protected/projects': typeof ProtectedProjectsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/enquiries/$id': typeof ProtectedEnquiriesIdRoute
  '/_protected/admins/': typeof ProtectedAdminsIndexRoute
  '/_protected/enquiries/': typeof ProtectedEnquiriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calculator-settings'
    | '/projects'
    | '/enquiries/$id'
    | '/admins/'
    | '/enquiries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calculator-settings'
    | '/projects'
    | '/'
    | '/enquiries/$id'
    | '/admins'
    | '/enquiries'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/calculator-settings'
    | '/_protected/projects'
    | '/_protected/'
    | '/_protected/enquiries/$id'
    | '/_protected/admins/'
    | '/_protected/enquiries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/calculator-settings': {
      id: '/_protected/calculator-settings'
      path: '/calculator-settings'
      fullPath: '/calculator-settings'
      preLoaderRoute: typeof ProtectedCalculatorSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/projects': {
      id: '/_protected/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedProjectsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admins/': {
      id: '/_protected/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof ProtectedAdminsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/enquiries/': {
      id: '/_protected/enquiries/'
      path: '/enquiries'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof ProtectedEnquiriesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/enquiries/$id': {
      id: '/_protected/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/enquiries/$id'
      preLoaderRoute: typeof ProtectedEnquiriesIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedCalculatorSettingsRoute: typeof ProtectedCalculatorSettingsRoute
  ProtectedProjectsRoute: typeof ProtectedProjectsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedEnquiriesIdRoute: typeof ProtectedEnquiriesIdRoute
  ProtectedAdminsIndexRoute: typeof ProtectedAdminsIndexRoute
  ProtectedEnquiriesIndexRoute: typeof ProtectedEnquiriesIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCalculatorSettingsRoute: ProtectedCalculatorSettingsRoute,
  ProtectedProjectsRoute: ProtectedProjectsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedEnquiriesIdRoute: ProtectedEnquiriesIdRoute,
  ProtectedAdminsIndexRoute: ProtectedAdminsIndexRoute,
  ProtectedEnquiriesIndexRoute: ProtectedEnquiriesIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
